### ISSUE TITLE
 Add support for Forums in "Course page further information"

### ISSUE THREAD

**Issue by timbahula-horizon** [gjb2048/moodle-format_topcoll#105]
As discussed in the [Moodle forum](https://moodle.org/mod/forum/discuss.php?d=406215#p1642071), I'll second the request to have an option to display further information on the course page about any grading that is required on a forum with whole forum grading.

![image](https://user-images.githubusercontent.com/46726396/124802926-7cc57a00-df26-11eb-8794-c66eff1f2ddb.png)

**Comment by gjb2048** [comment]
@timbahula-horizon Thanks for the request, would you like to fund my time for this please?

**Comment by ghost** [comment]
@gjb2048 , for my part, I would love to. However, I'll need to sell this to my manager. He'll want to know the approximate cost (hundreds or thousands) and rough timeframe (days or weeks).

**Comment by gjb2048** [comment]
@timbahula-horizon Thank you for getting back to me.  Pragmatically, it will take me 40 - 60% of the time to work out an 'approximate cost' due to the nature of software development, i.e. understanding the time it will take to complete a bespoke piece of work requires fully understanding the problem and what the solution is.  So at the moment, my closest estimate is a two to three figure sum (in GBP) that represents the time to be taken on the work (chargeable).  Actual time from start to finish all depends on the other work that I have on at the time (committed to before start).  I need to be sure that your manager is serious about this and we've agreed terms before I spend what will be a reasonable amount of time on an approximate estimate.

**Comment by ghost** [comment]
Yes, @gjb2048 , that makes sense. You've given me a range I can work with for now. I'll get back to you after I've consulted. There's some vacation happening so I expect that it will take a couple of weeks.

**Comment by ghost** [comment]
Followed up via PM via your user profile on moodle.org. Advise me if there is another means of communication that you would prefer.

**Comment by gjb2048** [comment]
@timbahula-horizon Thanks Tim, I've just messaged you back with a contact eMail etc.

**Comment by gjb2048** [comment]
All done and released.
