### ISSUE TITLE
Plugin for moodle v4 .1

### ISSUE THREAD

**Issue by deesonlee** [gjb2048/moodle-format_topcoll#132]
Is there a version of this plugin compatible with Moodle 4.1, looking at https://moodle.org/plugins/format_topcoll there doesn't seem to be a release marked as compatible yet.

Page says;
```
Release 400.1.2
Moodle 4.0
```

**Comment by gjb2048** [comment]
@deesonlee Yes and has been since last year.  You need to set your Moodle version to 4.1:

![Screenshot 2023-04-05 105354](https://user-images.githubusercontent.com/1058419/230048390-33ce5953-185b-4318-b585-4105d218ebb0.png)
...
![Screenshot 2023-04-05 105424](https://user-images.githubusercontent.com/1058419/230048465-1e9f0a27-e0ee-462e-a955-f8092f4a6997.png)

G
