### ISSUE TITLE
Port accessibility commits back to the MOODLE_35 branch

### ISSUE THREAD

**Issue by rhell4** [gjb2048/moodle-format_topcoll#57]
Hi @gjb2048 
Our client that requires the accessibility changes I had made are still on 3.5, would it be possibly for you to port the changes back to the MOODLE_35 branch?

Thanks,
Rossco

**Comment by gjb2048** [comment]
Hi Rossco,

I like to release enhancements first at the top branch, currently 'master' for Moodle 3.6, wait a while and get feedback so that if there is an issue then I don't spend more time fixing lots of branches.  So I'll release the M3.6 version soon and then see how things go over the next few weeks / month etc.

Gareth

**Comment by gjb2048** [comment]
Done.
