### ISSUE TITLE
config.php not needed

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-format_topcoll#97]
Following on from #96 and looking at 'get_default_blocks()' in '/course/format/formatlegacy.php' then the file is not needed as 'get_default_blocks()' in lib.php is used instead and CT inherits from format_base not format_legacy.

**Comment by badmechanic** [comment]
I apologize - but I don't understand what you're telling me/asking me.
All I did with get_default_blocks (which is being used) - is make the definition of the right block conditional on the
value set by the settings ($use_def_blocks).

So, I did nothing to affect the method/call to get_default_blocks - I only changed the flow within the subroutine to use the
configuration in $use_def_blocks (which I intend to change to "use-def-blocks", as per reading the output of testing.
I'll also see what can be done with the tabs defined.  I thought the tabs were "as-is" but maybe my vim editor jammed them in.
Please just reject the submissions, and I'll redo them.
I"ll wait until I hear from you on that.

So
1) Lef me know what you want done about the issue mentioned below re: get_default_blocks.
2) I'll fix the variable name.
3) I'll fix the spacing ( to remove tabs).

Is that a workable plan?

________________________________

From: Gareth J Barnard ***@***.***>
Sent: Tuesday, April 27, 2021 9:36 AM
To: gjb2048/moodle-format_topcoll ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gjb2048/moodle-format_topcoll] config.php not needed (#97)


Following on from #96<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgjb2048%2Fmoodle-format_topcoll%2Fpull%2F96&data=04%7C01%7C%7C0f800f0b8812476f7db208d9095febda%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637551129838797467%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tuq4GCei0UWlenT7Bwp9N6wF1Zf2b38L0zrXBdYouKY%3D&reserved=0> and looking at 'get_default_blocks()' in '/course/format/formatlegacy.php' then the file is not needed as 'get_default_blocks()' in lib.php is used instead and CT inherits from format_base not format_legacy.

**Comment by gjb2048** [comment]
@badmechanic This issue is for me.  I'll comment on #96.

**Comment by badmechanic** [comment]
OK - the "badmechanic" idea is bad.  It was a github account for me to work and play.  Alll junk in there being public.
When I decided I'd use things for real - it would be with github.com/John-Joubert.

Well - I messed up, and didn't change one of the settings in my home directory, and somehow - I was posting to "John-Joubert" - but the pull requests were looking like they were from badmechanic.

I believe I've fixed this.  So the next post should be better.

I've fixed the comments, spacing, and got rid of the variable as requested in lib.php.
I've also deleted the file that you requested (Changes_blocks_optional.md).
I figure you've read my notes by now - so I'll just kill it off.

I don't know how to put changes for both the Moodle 3.9 and Moodle 3.10 versions in one commit,
as the language files are different in the two branches that you provided (MOODLE_39 vs master)- but the lib.php and settings.php files are identical, however.

So, I'll submit as two sub-commits, one for each branch.

Alternatively, I can provide three - one for the two files in common, and one each for just the language files...

Sadly, I'm too much of a noob to understand how to provide it all in a single commit because the language files between MOODLE_39 and master are different.  I can re-check that this is indeed a fact (I was surprised by this, frankly).  So - before resubmitting - I will double-check that my facts are correct for this.

Suggestion.
Would you just like a bash script to run to add the language file additions to the end of the files instead???
I'm quite skilled at bash scripting (it's my everyday tool) - and I can just submit that in the main directory as "fix_lang_files.sh" and I can make it smart that if the definitions already exists, it won't re-add the definitions... let me know your thoughts.   If it I did it this way - I can put everything in a single commit.  A change in settings.php, a change in lib.php, and a .sh script file to fix the language files.




________________________________

**Comment by gjb2048** [comment]
@badmechanic Ok, I'm getting annoyed now!  Please comment on #96, this issue is nothing to do with you.

**Comment by badmechanic** [comment]
It sounds like I messed something up.

Very sorry!

John

________________________________

**Comment by gjb2048** [comment]
Done in M3.9+ versions.
